# Generated by Django 4.1.6 on 2023-02-10 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment_hive_user_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.hive'),
            preserve_default=False,
        ),
    ]
