# Generated by Django 4.1.6 on 2023-02-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment_hive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(verbose_name='comment date'),
        ),
    ]
