# Generated by Django 4.1.6 on 2023-02-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hive',
            name='user',
        ),
    ]
