# Generated by Django 4.1.6 on 2023-02-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.address'),
        ),
    ]
