# Generated by Django 4.1.6 on 2023-02-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_hive_user'),
        ('main_app', '0008_photo'),
    ]

    operations = [
    ]
