# Generated by Django 4.1.6 on 2023-02-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_comment_date_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
