# Generated by Django 4.1.6 on 2023-02-16 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0010_remove_comment_date_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='users',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.AddField(
            model_name='dislike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hive'),
        ),
        migrations.AlterField(
            model_name='like',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hive'),
        ),
    ]
