# Generated by Django 4.1.2 on 2024-08-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_comment_user'),
        ('main_app', '0011_hive_photo_url'),
        ('main_app', '0011_remove_dislike_created_at_remove_dislike_updated_at_and_more'),
    ]

    operations = [
    ]
